name: PR Request Summarizer

on:
  pull_request

jobs:
  summarize:
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout repository"
        uses: actions/checkout@v3

      - name: "Run python script"
        uses: ./
        env:
          GEMINI_API_KEY: ${{secrets.GEMINI_API_KEY}}